version: '3.8'

services:
  phoenix-cms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}